apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 3000
  selector:
    app: {{ .Release.Name }}
